spring.application.name=app
spring.security.user.password=demo@123
spring.security.user.name=admin

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa

spring.app.jwtSecret=mySecretKey07!#9123738@codevalue67
spring.app.jwtExpirationMs=86400000